# NoDespawn-OG 3.0 Config.

# Should item despawning be completely disabled on player death?
disable-death-despawns: true

# How long should all other entities take to despawn? (in ticks, seconds (s), minutes (m), or hours (h))
# The vanilla behavior is 300 seconds, or 5 Minutes (roughly 6000 ticks).
# If the format of this option is invalid, NoDespawn-OG will default to 5 minutes.
time-to-despawn: 5m 

# If disable despawns is set to false, how long (in ticks, seconds (s), minutes (m), or hours (h)) 
# should items dropped on death last until despawn?
# If higher than the max or lower than the min, defaults to the value of time-to-despawn above.
time-to-death-despawns: 20m